version: "3.8"
services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    networks:
      - mynetwork
  newHotel:
    depends_on:
      - mysqldb
    build: ./newHotel
    restart: on-failure
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/hotels?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - 8888:8888
    networks:
      - mynetwork